/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TanqueController;
import java.awt.Color;
import javax.swing.Timer;
import model.ControlNivel;
import model.TransmisorNivel;
import model.Valvula;

/**
 *
 * @author maria
 */
public class TanqueAgua extends javax.swing.JFrame {

    /**
     * Creates new form TanqueAgua
     */
    private Valvula valvula;
    private TransmisorNivel transmisorNivel;
    private ControlNivel controlNivel;
    private TanqueController tanqueController;
    
    public TanqueAgua() {
        initComponents();
        valvula = new Valvula();
        transmisorNivel = new TransmisorNivel();
        controlNivel = new ControlNivel(valvula);
        tanqueController = new TanqueController(Tanque, TuberiaCasa, TuberiaControlNivel, TuberiaTransmisorDeNivel, TuberiaValvula, Valvula, txtPorcentaje, ButtonStart, ColorValvula);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TransmisorNivel = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        ControladorDeNivel = new javax.swing.JLabel();
        ColorValvula = new javax.swing.JPanel();
        Tanque = new javax.swing.JProgressBar();
        Valvula = new javax.swing.JLabel();
        TuberiaValvula = new javax.swing.JProgressBar();
        TuberiaControlNivel = new javax.swing.JProgressBar();
        Casa = new javax.swing.JLabel();
        TuberiaTransmisorDeNivel = new javax.swing.JProgressBar();
        ButtonStart = new javax.swing.JButton();
        TuberiaCasa = new javax.swing.JProgressBar();
        Fondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TransmisorNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transmisor-nivel-2.png"))); // NOI18N
        getContentPane().add(TransmisorNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 150));

        txtPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 200, 115, 70));

        ControladorDeNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/control-nivel.png"))); // NOI18N
        getContentPane().add(ControladorDeNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        ColorValvula.setBackground(new java.awt.Color(255, 51, 51));
        ColorValvula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout ColorValvulaLayout = new javax.swing.GroupLayout(ColorValvula);
        ColorValvula.setLayout(ColorValvulaLayout);
        ColorValvulaLayout.setHorizontalGroup(
            ColorValvulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        ColorValvulaLayout.setVerticalGroup(
            ColorValvulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        getContentPane().add(ColorValvula, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 25, 50, 50));
        ColorValvula.getAccessibleContext().setAccessibleDescription("");

        Tanque.setBackground(new Color(204, 204, 204));
        Tanque.setOrientation(1);
        Tanque.setToolTipText("");
        Tanque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 469, 440));
        Tanque.setForeground(new Color(51, 204, 255)); // Color azul (agua)
        Tanque.setMinimum(0);
        Tanque.setMaximum(100);
        Tanque.setValue(0);

        // Añadir el JProgressBar al JFrame

        Valvula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llave-de-cierre.png"))); // NOI18N
        getContentPane().add(Valvula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 120));
        getContentPane().add(TuberiaValvula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 20));
        getContentPane().add(TuberiaControlNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 20, 300));

        Casa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        getContentPane().add(Casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, -1));
        getContentPane().add(TuberiaTransmisorDeNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 40, 20));

        ButtonStart.setText("Iniciar Simulacion");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 130, 40));
        getContentPane().add(TuberiaCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 120, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fond2.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        // TODO add your handling code here:
       tanqueController.iniciarSimulacion();
       
    }//GEN-LAST:event_ButtonStartActionPerformed

    private void txtPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TanqueAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TanqueAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TanqueAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TanqueAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TanqueAgua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonStart;
    private javax.swing.JLabel Casa;
    private javax.swing.JPanel ColorValvula;
    private javax.swing.JLabel ControladorDeNivel;
    private javax.swing.JLabel Fondo;
    private javax.swing.JProgressBar Tanque;
    private javax.swing.JLabel TransmisorNivel;
    private javax.swing.JProgressBar TuberiaCasa;
    private javax.swing.JProgressBar TuberiaControlNivel;
    private javax.swing.JProgressBar TuberiaTransmisorDeNivel;
    private javax.swing.JProgressBar TuberiaValvula;
    private javax.swing.JLabel Valvula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
